parameters: 
- name: 'workingDir'
  type: string 

stages: 
- stage: run
  displayName: 'Run in ${{ parameters.workingDir }}'

  jobs:

  - job: run-job

    steps: 
      - script: echo "Hello from '${{ parameters.workingDir }}'"

      - script: npm install
        workingDirectory: ${{ parameters.workingDir }}

      - script: npm run chalk
        workingDirectory: ${{ parameters.workingDir }}