# Build numbering format
name: $(BuildID)

variables:
  - name: working-dir
    value: 'service-a/'

trigger:
  branches:
    include:
      - master
      - feat/*
  paths:
    include:
      - 'service-a/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello from 'service-a' this is a test"

- script: npm install
  workingDirectory: $(working-dir)

- script: npm run chalk
  workingDirectory: $(working-dir)