# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feat/*
  paths:
    include:
      - 'service-a/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from 'a' this is a test"